//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public string CourseName { get; set; }
        public int CourseId { get; set; }
        public string Professor { get; set; }
        public int Credit { get; set; }
        public int Capacity { get; set; }
        public string Location { get; set; }
        public System.DateTime Time { get; set; }
        public string Status { get; set; }
    }
}
