//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int StudentID { get; set; }
        public int PersonId { get; set; }
        public string Major { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual Person Person { get; set; }
    }
}
