//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEnrollementStatu
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int Credit { get; set; }
        public string Location { get; set; }
        public System.DateTime Time { get; set; }
        public string CourseStatus { get; set; }
        public Nullable<int> CurrentlyEnrolled { get; set; }
        public string CourseEnrollement { get; set; }
    }
}
