//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ToDoEntities3 : DbContext
    {
        public ToDoEntities3()
            : base("name=ToDoEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ToDo> ToDoes { get; set; }
        public virtual DbSet<ShowAll> ShowAlls { get; set; }
        public virtual DbSet<ShowComplete> ShowCompletes { get; set; }
        public virtual DbSet<ShowIncomplete> ShowIncompletes { get; set; }
    
        public virtual int RemoveItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveItem");
        }
    
        public virtual int UpdateItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateItem");
        }
    }
}
